apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.kserve.io/stop: 'false'
    security.opendatahub.io/enable-auth: 'false'
    openshift.io/description: ''
    openshift.io/display-name: gpt-oss-20b
    serving.kserve.io/deploymentMode: RawDeployment
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/hardware-profile-name: gpu-profile
    opendatahub.io/model-type: generative
  name: gpt-oss-20b
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/genai-asset: 'true'
    networking.kserve.io/visibility: exposed
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - '--enable-expert-parallel'
        - '--gpu-memory-utilization=0.86'
        - '--dtype=auto'
        - '--max-model-len=21024'
        - '--max-num-seqs=24'
        - '--max-num-batched-tokens=1024'
        - '--enable-prefix-caching'
        - '--async-scheduling'
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '4'
          memory: 16Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '1'
          memory: 6Gi
          nvidia.com/gpu: '1'
      runtime: gpt-oss-20b
      storageUri: 'pvc://gpt-oss-20b-pvc/'