apiVersion: batch/v1
kind: Job
metadata:
  name: load-{{ .Values.model.name }}-copy
spec:
  template:
    spec:
      containers:
      - name: copy-model
        # Use the target model image itself
        image: {{ .Values.model.image }}
        command:
        - /bin/sh
        - -c
        - |
          echo "Copying model weights from container to PVC..."
          cp -a /models/. /mnt/pvc/
          echo "Done. Contents of PVC:"
          ls -lh /mnt/pvc/
        volumeMounts:
        - name: model-volume
          mountPath: /mnt/pvc
      restartPolicy: Never
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: {{ .Values.model.name }}-pvc
