{{- if .Values.pvcInspector.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector-{{ .Values.model.name }}
spec:
  containers:
  - name: inspector
    image: registry.access.redhat.com/ubi9/ubi-minimal:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: data
      mountPath: /mnt/pvc
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: {{ .Values.model.name }}-pvc
{{- end }}
